config/routes.rb
Donate::Application.routes.draw do
  
  devise_for :hospitals
  devise_for :users
  resources :users
  
  resources :hospitals
  resources :banked_bloods
  resources :hospitals, :users do
    collection do
      resources :banked_bloods, :only => [:create, :update, :destroy]
    end
  end
  resources :kidneys
  resources :hospitals, :users do
    collection do
      resources :kidneys, :only => [:create, :update, :destroy]
    end
  end
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  root  'static_pages#home'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@hospital = current_hospital
  	@blooddonations = BankedBlood.paginate(page: params[:page])
  	@kidneydonations = Kidney.paginate(page: params[:page])
  	@user = current_user
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Contact Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>



  <% if signed_in? %>
  <div class="row">
    <% if user_signed_in? %>
    <section>
      <h1>
        <% if hospital_signed_in? %>
        <%= link_to @user.name %>
        <% end %>
        <%= link_to @user.zip, @user%>
        <% if signed_in? %>
        <% if current_user.admin? && !current_user?(@user) %>
        | <%= link_to "delete", @user, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  <% end %>
        <% end %>
      </h1>  
    </section>
    <section>
      <b>Age        :</b> <%= @user.age %> <br>
      <b>Gender     :</b> <%= @user.gender %> <br>
      <b>Bloodgroup :</b> <%= @user.bloodgroup %> <br>
      <% if hospital_signed_in? || current_user?(@user) %>
      <b>Mobile     :</b> <%= @user.phone %> <br>
      <b>Address    :</b> <%= @user.address %> <br>
      <b>City       :</b> <%= @user.city %> <br>
      <% end %>
    </section>

    <% end %>


   <% if hospital_signed_in? %>
     <aside class="span4">
    <section>
      <h1>
        
        <%= link_to @hospital.hospital_name, @hospital%>
        <% if signed_in? %>
        <% if current_hospital.admin? && !current_hospital?(@hospital) %>
        | <%= link_to "delete", @hospital, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  <% end %>
        <% end %>
      </h1>  
    </section>
    <section>
      <b>Doctor Incharge       :</b> <%= @hospital.doctor_incharge %> <br>
      <b>Contact               :</b> <%= @hospital.hospital_phone %> <br>
      <b>Address               :</b> <%= @hospital.hospital_address %> <br>
      <b>City                  :</b> <%= @hospital.hospital_city %> <br>
      <b>Postal code           :</b> <%= @hospital.hospital_zip %> <br>
    </section>
  </aside>
<div class="span4">
  <%= will_paginate @blooddonations %>
Blood: 
<ul class="users">
  <% @blooddonations.each do |blooddonation| %>
    <li>
      <b>Postal code: </b> <%= blooddonation.hospital.hospital_zip %><br> 
      <b>Donor:</b>  <%= blooddonation.donor %><br>
      <b>Bloodgroup:</b>  <%= blooddonation.bloodgroup %><br>
      <b>Donated to:</b>  <%= blooddonation.donated_to %><br>
    </li>
  <% end %>
</ul>
</div>
<%= will_paginate @blooddonations %>
   <div>
  <%= will_paginate @kidneydonations %>
Kidney: 
<ul class="users">
  <% @kidneydonations.each do |kidneydonation| %>
    <li>
      <b>Postal code: </b> <%= kidneydonation.hospital.hospital_zip %> <br>
      <b>Donor:</b>  <%= kidneydonation.kidneydonor %><br>
      <b>Bloodgroup:</b>  <%= kidneydonation.kidneybloodgroup %><br>
      <b>Donated to:</b>  <%= kidneydonation.kidneydonated_to %><br>
      <b>Bonemarrow:</b>  <%= kidneydonation.kidneybonemarrow %><br>
      <b>Tissue type:</b>  <%= kidneydonation.kidneytissue_type %><br>
    </li>
  <% end %>
</ul>
</div>
<%= will_paginate @kidneydonations %>

     
   <% end %>
     
     
  </div>



  <%else %>

  	<div class="center hero-unit">
    	<h1>Donate</h1>
    	<h2>Donated blood and organs database</h2>
       
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% elsif hospital_signed_in? %>
        Signed in as <%= current_hospital.email %>. Not you?
      <%= link_to "Sign out", destroy_hospital_session_path, :method => :delete %>
      <% else %>
      <%= link_to "Donor Sign up", new_user_registration_path, class: "btn btn-primary" %>
      <%= link_to "Hospital Sign up", new_hospital_registration_path, class: "btn btn-danger" %>

      <% end %>
      
  
    	
    </div>

    <%end%>
  </body>
</html>