config/routes.rb
Donate::Application.routes.draw do
  
  devise_for :hospitals
  devise_for :users
  resources :users
  
  resources :hospitals
  resources :banked_bloods
  resources :hospitals, :users do
    collection do
      resources :banked_bloods, :only => [:create, :update, :destroy]
    end
  end
  resources :kidneys
  resources :hospitals, :users do
    collection do
      resources :kidneys, :only => [:create, :update, :destroy]
    end
  end
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  root  'static_pages#home'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Donate",   root_path %>
    by <a href="https://www.facebook.com/devangtgr8">Devang Gupta</a>
      ,<a href="https://www.facebook.com/shivamsatija04">Abhimanyu Mittal </a>
      <a href="https://www.facebook.com/shivamsatija04">Sagar Ghai </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Donate", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
          <li><%= link_to "Home", current_user %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Hospitals", hospitals_path %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <% if user_signed_in? %>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
              <% end %>
              <% if hospital_signed_in? %>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_hospital %></li>
                <li><%= link_to "Settings", edit_hospital_registration_path(current_hospital) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_hospital_session_path, method: "delete" %>
                </li>
              </ul>
              <% end %>
            </li>
          <% else %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Hospitals", hospitals_path %>
            <li><%= link_to "User sign in", new_user_session_path %></li>
            <li><%= link_to "Hospital sign in", new_hospital_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>

</head>
<body>
	<div>
		<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      	<% end %>
		<%= render 'layouts/header' %>
	
		<div class="container">

			<%= yield %>

		</div>

		<%= render 'layouts/footer' %>

		<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>